import express from "express";
const router = express.Router();
import * as controller from "../../controllers/admin/role.controller";
import { createRole } from "../../validates/admin/role.validate";
router.get("/", controller.index);
router.get("/create", controller.create);
router.post("/create", createRole,controller.createPost);
router.get("/permissions", controller.permissions);
router.patch("/permissions", controller.permissionsPatch);
export const roleRoute = router;